# Generated by Django 3.2.4 on 2021-08-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrysite',
            name='country_code',
            field=models.SlugField(help_text='Unique country code (e.g. NL, UK, DE)', max_length=10, unique=True),
        ),
    ]
