# Generated by Django 3.2.4 on 2021-09-02 19:25

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0003_alter_countrysite_default_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrysite',
            name='icon',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='static'), upload_to='img/site_icons/'),
        ),
    ]
