# Generated by Django 3.2.4 on 2021-09-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0004_countrysite_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countrysite',
            name='icon',
        ),
        migrations.AlterField(
            model_name='countrysite',
            name='default_language',
            field=models.CharField(help_text='Default language to be displayed on this country site', max_length=25),
        ),
    ]
