# Generated by Django 3.2.7 on 2021-11-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0005_auto_20210906_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrysite',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
